### ISSUE TITLE
not working properly

### ISSUE THREAD

**Issue by Surfingnet** [mrdotb/docker-42norminette#3]
Hi, great job dude u did nice work. 

The norminette is working when using "docker run -v $PWD:/temp --rm -it mrdotb/42norminette temp/xxx.c" 

But i cant use wildcards with it so I installed your stuff in my $PATH (same as yours, ~/.local/bin) and now im getting an error:

<img width="601" alt="Capture d’écran 2020-10-21 à 12 06 37" src="https://user-images.githubusercontent.com/10564571/96706474-ebfa3e80-1396-11eb-969c-e2b26de28d86.png">

Did I miss something ?

**Comment by mrdotb** [comment]
Il te manque le binaire realpath qui n'existe pas sur mac
Je vois que tu es sur un mac il faudrait rajouter ca pour que ca marche.
https://stackoverflow.com/questions/3572030/bash-script-absolute-path-with-os-x
Par contre si tu as access a internet rapide je te conseil d'utiliser plutôt la nominette online officiel https://github.com/42Paris/norminette car malheureusement le dump que j’utilise n'est pas a jour. Il me semble qu'il manque un cas sur les structures.
J'utilisais ca parce que mon internet était vraiment lent.

**Comment by Surfingnet** [comment]
J'ai désinstallé la norminette officielle parce qu'impossible pour elle de se connecter à norminette.42network.org pour une raison obscure. Je ne sais pas si cest une histoire de login mais je n'ai plus de compte intra alors ca n'aide pas. Je vais jeter un oeil à ton lien. Merci pour la réponse expressss!

**Comment by Surfingnet** [comment]
Ton lien m'a bien aidé, installer CoreUtils a résolu le problème. Encore bravo pour ton boulot.
